### ISSUE TITLE
Rather a skeleton

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/nextcloud-whiteboard#1]
Will this be one of your productive servlets and have a better compose.yml or is it advisable to build my own?

**Comment by tiredofit** [comment]
Hopefully this will become something that gets maintained regularly - right now its in a pure feasibility study stage and likely will for a few more months until I can have a team evaluate the whiteboard component to take the place of other proprietary solutions.. In the meantime this may help?



```
  nextcloud-example-com-whiteboard:
    image: tiredofit/nextcloud-whiteboard
    container_name: nextcloud-example-com-whiteboard
    labels:
      - traefik.enable=true
      - traefik.http.routers.wb-nextcloud-example-com.rule=Host(`wb.nextcloud.example.com`)
      - traefik.http.services.wb-nextcloud-example-com.loadbalancer.server.port=3002
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=nextcloud-example-com-whiteboard
      - CONTAINER_ENABLE_LOGSHIPPING=FALSE
      - CONTAINER_ENABLE_MONITORING=FALSE
      - NEXTCLOUD_URL=https://nextcloud.example.com
      - JWT_SECRET_KEY=super-DUPER-secret-KEY
    networks:
      - proxy
      - services
```
